// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOPuBJN1cueddl6vPwx4-wOMggtnXdJKo',
    appId: '1:557809837381:web:671a88d02948c816caca2c',
    messagingSenderId: '557809837381',
    projectId: 'parking4u-b729e',
    authDomain: 'parking4u-b729e.firebaseapp.com',
    storageBucket: 'parking4u-b729e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAljVxv-utGRJSE-RhUwZUtDynwJVb12FY',
    appId: '1:557809837381:android:72e37c6c8332aa11caca2c',
    messagingSenderId: '557809837381',
    projectId: 'parking4u-b729e',
    storageBucket: 'parking4u-b729e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOPuBJN1cueddl6vPwx4-wOMggtnXdJKo',
    appId: '1:557809837381:web:4d9d014a3899659bcaca2c',
    messagingSenderId: '557809837381',
    projectId: 'parking4u-b729e',
    authDomain: 'parking4u-b729e.firebaseapp.com',
    storageBucket: 'parking4u-b729e.firebasestorage.app',
  );
}
